# Generated by Django 5.1.1 on 2024-10-14 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=80)),
                ('postal_code', models.CharField(help_text='Enter a 6-digit number', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter exactly 6 digits.')])),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='Address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_outlet.address'),
        ),
    ]
